#!/bin/sh

set -e 

#old compatibility workaround for kali-menu menu entries
if [ -e "/usr/share/applications/kali-*" ]; then
	rm /usr/share/applications/kali-*.desktop
fi
if [ -e "/etc/apt/apt.conf.d/99kali-menu" ]; then
	rm /etc/apt/apt.conf.d/99kali-menu
fi
if [ -e "/usr/share/kali-menu/update-kali-menu" ]; then
	rm /usr/share/kali-menu/update-kali-menu
	rm -r /usr/share/kali-menu/
fi
